#!/usr/bin/env bash
# Generate test/dune.inc from test_*.ml files.
# Workers only need to add their test_*.ml file - no manual dune edits.

cd "$(dirname "$0")"

cat > dune.inc <<'HEADER'
; AUTO-GENERATED by gen_dune.sh - do not edit manually.
; To add a new module's tests, just create test/test_<module>.ml
; and run: make build (or ./test/gen_dune.sh)
HEADER

for f in test_*.ml; do
  name="${f%.ml}"
  cat >> dune.inc <<EOF

(test
 (name ${name})
 (modules ${name})
 (libraries core alcotest yojson s2 test_helpers base_quickcheck)
 (deps
  (glob_files fixtures/*.json))
 (preprocess
  (pps ppx_jane))
 (flags
  (:standard)))
EOF
done
