(** [S2_builder] assembles polygonal geometry from edges. It accepts input edges, snaps
    them to a discrete set of sites, and hands the resulting snapped edge graph to one or
    more {!Layer.t} implementations for assembly into the desired output type (e.g. an
    {!S2_polygon.t}).

    The builder preserves the topology of the input under a guaranteed [snap_radius]: no
    vertex moves further than that radius, no pair of output vertices is closer than
    [min_vertex_separation], and edges and non-incident vertices are separated by at least
    [min_edge_vertex_separation]. See {!Snap_function} for the precise contract.

    This port covers the surface required by [s2_boolean_operation]. Specifically:
    directed edges; the polygon layer; identity snap function. The following are deferred
    with TODO markers in the source: undirected edges,
    [IntLatLngSnapFunction]/[S2CellIdSnapFunction] (stubbed as raising), forced vertices,
    labels, edge-chain simplification, memory tracking, and lax/polyline layers. *)

open Core

(** Error reported by the builder or a layer. *)
module Error : sig
  type t =
    { code : string
    ; message : string
    }
  [@@deriving sexp_of]

  val ok : t
  val is_ok : t -> bool
  val create : code:string -> message:string -> t
end

(** Directed vs undirected input edges. Only [Directed] is fully implemented in this port;
    [Undirected] raises when hit. *)
module Edge_type : sig
  type t =
    | Directed
    | Undirected
  [@@deriving sexp_of, equal]
end

(** How to treat degenerate edges (an edge from a vertex to itself). *)
module Degenerate_edges : sig
  type t =
    | Discard
    | Discard_excess
    | Keep
  [@@deriving sexp_of, equal]
end

(** How to treat duplicate edges. *)
module Duplicate_edges : sig
  type t =
    | Merge
    | Keep
  [@@deriving sexp_of, equal]
end

(** How to treat sibling pairs (an edge and its reverse). *)
module Sibling_pairs : sig
  type t =
    | Discard
    | Discard_excess
    | Keep
    | Require
    | Create
  [@@deriving sexp_of, equal]
end

(** Options controlling how {!Graph.t} is constructed for a given layer. *)
module Graph_options : sig
  type t =
    { edge_type : Edge_type.t
    ; degenerate_edges : Degenerate_edges.t
    ; duplicate_edges : Duplicate_edges.t
    ; sibling_pairs : Sibling_pairs.t
    ; allow_vertex_filtering : bool
    }
  [@@deriving sexp_of]

  (** The default options keep every edge, producing the least surprising output. *)
  val default : t

  val create
    :  edge_type:Edge_type.t
    -> degenerate_edges:Degenerate_edges.t
    -> duplicate_edges:Duplicate_edges.t
    -> sibling_pairs:Sibling_pairs.t
    -> t

  val equal : t -> t -> bool
end

(** Sentinel value larger than any valid input edge id. *)
val k_max_input_edge_id : int

(** Sentinel for graph edges created without a corresponding input edge (e.g., siblings
    generated by [Sibling_pairs.Create]). *)
val k_no_input_edge_id : int

(** A lexicon maps a non-negative "set id" to a sorted set of integers (input edge ids or
    labels). Used by {!Graph.t} to share storage across many edges that map to the same
    set. *)
module Id_set_lexicon : sig
  type t

  val create : unit -> t

  (** [empty_set_id] is the canonical id of the empty set. It is always [0]. *)
  val empty_set_id : int

  (** Add a sorted set of ids and return a lexicon-unique id. *)
  val add : t -> int array -> int

  (** Add a singleton. *)
  val add_singleton : t -> int -> int

  (** Look up a set by id. Returns a view of the underlying ids. *)
  val id_set : t -> int -> int array

  val clear : t -> unit
  val copy : t -> t
end

(** An {!S2_builder} {!Graph.t} represents the snap-rounded edge graph passed to a
    {!Layer.t} for assembly. Vertices are numbered sequentially starting at zero; edges
    are (origin, destination) vertex id pairs, sorted lexicographically so that all edges
    outgoing from a vertex form a contiguous range. *)
module Graph : sig
  (** A graph edge: a pair of vertex ids. Boxed so that edges can be stored in ordinary
      [array]s; use {!src} / {!dst} accessors. *)
  module Edge : sig
    type t =
      { src : int
      ; dst : int
      }

    val create : src:int -> dst:int -> t
    val src : t -> int
    val dst : t -> int
    val reverse : t -> t
    val equal : t -> t -> bool
    val compare : t -> t -> int
  end

  type t =
    { options : Graph_options.t
    ; vertices : S2_point.t array
    ; edges : Edge.t array
    ; input_edge_id_set_ids : int array
    ; input_edge_id_set_lexicon : Id_set_lexicon.t
    ; is_full_polygon_predicate : t -> bool * Error.t
    }

  val options : t -> Graph_options.t
  val num_vertices : t -> int
  val vertex : t -> int -> S2_point.t
  val num_edges : t -> int
  val edge : t -> int -> Edge.t

  (** [get_in_edge_ids g] returns the edge ids sorted lexicographically by [(dst, src)]. *)
  val get_in_edge_ids : t -> int array

  (** [get_sibling_map g] returns a map from each edge id to its sibling. Requires that
      every edge has a sibling (either [Sibling_pairs.Require] or [Sibling_pairs.Create]). *)
  val get_sibling_map : t -> int array

  (** [input_edge_ids g e] is the set of input edge ids that were snapped to graph edge
      [e]. *)
  val input_edge_ids : t -> int -> int array

  val min_input_edge_id : t -> int -> int

  (** [is_full_polygon g] runs the full-polygon predicate. It returns [(is_full, err)] -
      when [g] consists only of degenerate edges and/or sibling pairs, [is_full] indicates
      whether the result should be the full polygon. *)
  val is_full_polygon : t -> bool * Error.t

  (** In-place edge transformation applying a given [Graph_options.t] to an unsorted list
      of edges. Discards degenerates, merges duplicates, and handles sibling pairs per the
      options. Mutates the [options] value if the undirected-to-directed conversion
      applies ([Sibling_pairs.Require] or [Sibling_pairs.Create] with undirected edges). *)
  val process_edges
    :  options:Graph_options.t ref
    -> edges:Edge.t array ref
    -> input_ids:int array ref
    -> id_set_lexicon:Id_set_lexicon.t
    -> Error.t

  (** Builds loops (as edge-id sequences) from a set of directed edges by making left
      turns at each vertex. Each repeated-vertex cycle is cut off (for [Simple]) or a
      repeated-edge cycle (for [Circuit]). *)
  module Loop_type : sig
    type t =
      | Simple
      | Circuit
  end

  val get_directed_loops : t -> Loop_type.t -> int array array * Error.t
end

(** A snap function controls the positions of output vertices. *)
module Snap_function : sig
  (** Maximum supported snap radius (approximately 7800 km, i.e., 70 degrees on the unit
      sphere). *)
  val k_max_snap_radius : unit -> S1_angle.t

  (** A snap function is a record of functions. We use a record because an abstract OCaml
      class hierarchy would add unnecessary allocation here; the number of concrete
      implementations is small. *)
  type t =
    { snap_radius : S1_angle.t
    ; min_vertex_separation : S1_angle.t
    ; min_edge_vertex_separation : S1_angle.t
    ; snap_point : S2_point.t -> S2_point.t
    }

  (** [identity ()] is the snap function with zero snap radius: every input point is
      preserved exactly. *)
  val identity : unit -> t

  (** [identity_with_radius r] is like {!identity} but with a non-zero snap radius, so
      that input vertices closer than [r] may be merged. *)
  val identity_with_radius : S1_angle.t -> t

  (** Stub for [IntLatLngSnapFunction]. Not implemented; raises on any use. *)
  val int_lat_lng : exponent:int -> t

  (** Stub for [S2CellIdSnapFunction]. Not implemented; raises on any use. *)
  val s2_cell_id : level:int -> t
end

(** Options controlling the builder itself. *)
module Options : sig
  type t =
    { snap_function : Snap_function.t
    ; edge_snap_radius : S1_angle.t
    ; intersection_tolerance : S1_angle.t
    ; split_crossing_edges : bool
    ; idempotent : bool
    }

  (** [default ()] uses [Snap_function.identity] with zero snap radius. *)
  val default : unit -> t

  (** [create ~intersection_tolerance ()] builds options from the given values.
      [intersection_tolerance] is required because [S1_angle.t] is unboxed and cannot
      appear in an optional argument default. Pass [S1_angle.zero] for no tolerance. *)
  val create
    :  ?snap_function:Snap_function.t
    -> ?split_crossing_edges:bool
    -> ?idempotent:bool
    -> intersection_tolerance:S1_angle.t
    -> unit
    -> t

  (** [max_edge_deviation t] is the maximum distance a point along an edge can move when
      snapped. Slightly larger than [edge_snap_radius]. *)
  val max_edge_deviation : t -> S1_angle.t
end

(** A layer receives the snapped edge graph and turns it into the layer's native geometry
    type (polygon, polyline, etc.). *)
module Layer : sig
  type t =
    { graph_options : Graph_options.t
    ; build : Graph.t -> Error.t
    ; name : string
    }
end

(** Predicate called when the output of a polygon layer consists only of degenerate edges
    and/or sibling pairs. Returns [true] iff the result should be interpreted as the full
    polygon. *)
type is_full_polygon_predicate = Graph.t -> bool * Error.t

(** The builder itself. Mutable. *)
type t

(** [create options] creates a builder with the given options. *)
val create : Options.t -> t

(** [options t] returns the builder's options. *)
val options : t -> Options.t

(** [start_layer t layer] starts a new output layer. All subsequent [add_*] calls
    contribute to this layer. *)
val start_layer : t -> Layer.t -> unit

(** [add_point t p] adds a degenerate edge [(p, p)] to the current layer. *)
val add_point : t -> S2_point.t -> unit

(** [add_edge t v0 v1] adds the edge [(v0, v1)] to the current layer. *)
val add_edge : t -> S2_point.t -> S2_point.t -> unit

(** [add_polyline t vertices] adds the edges of a polyline to the current layer. *)
val add_polyline : t -> S2_point.t array -> unit

(** [add_loop t vertices] adds the edges of a loop to the current layer. *)
val add_loop : t -> S2_point.t array -> unit

(** [add_shape t shape] adds every edge of [shape] to the current layer. *)
val add_shape : t -> S2_shape.t -> unit

(** [add_intersection t vertex] ensures that edges crossing near [vertex] snap to a common
    vertex. Requires that [options.intersection_tolerance] is positive. *)
val add_intersection : t -> S2_point.t -> unit

(** [add_is_full_polygon_predicate t predicate] records a predicate for the current layer.
    At most one predicate may be set per layer; later calls overwrite earlier ones. *)
val add_is_full_polygon_predicate : t -> is_full_polygon_predicate -> unit

(** [is_full_polygon_unspecified] is the default predicate: it reports an error indicating
    that no predicate has been supplied. *)
val is_full_polygon_unspecified : is_full_polygon_predicate

(** [is_full_polygon constant] is the predicate that always returns [constant]. *)
val is_full_polygon : bool -> is_full_polygon_predicate

(** [build t] runs the snap rounding and invokes each layer's [build] hook with the
    resulting {!Graph.t}. Returns {!Error.ok} on success. *)
val build : t -> Error.t
